from bas_engine.models.simulation import SimulationResult
import datetime

class ReportGenerator:

    def generate_markdown(self, sim: SimulationResult) -> str:
        report = []
        report.append(f"# SecureForge Simulation Report")
        report.append(f"**Simulation ID:** `{sim.id}`")
        report.append(f"**Name:** {sim.name}")
        report.append(f"**Target:** `{sim.target}`")
        report.append(f"**Status:** {sim.status.upper()}")
        
        started = sim.started_at.strftime("%Y-%m-%d %H:%M:%S UTC") if sim.started_at else "N/A"
        finished = sim.finished_at.strftime("%Y-%m-%d %H:%M:%S UTC") if sim.finished_at else "N/A"
        report.append(f"**Started:** {started}")
        report.append(f"**Finished:** {finished}")
        
        if sim.duration_s is not None:
            report.append(f"**Duration:** {sim.duration_s:.2f} seconds")

        report.append("\n## Executive Summary")
        validation = sim.metadata.get("detection_validation", {})
        if validation:
            attack_surface = validation.get("attack_surface", {})
            detection = validation.get("detection_simulation", {})
            
            report.append(f"- **Exposure Score:** {attack_surface.get('exposure_score', 'N/A')}/100")
            report.append(f"- **Simulated Detection Score:** {detection.get('detection_score', 'N/A')}/100")
            report.append(f"- **NIST Maturity Tier:** {detection.get('nist_maturity_tier', 'N/A')}")
            
            report.append("\n### Findings Overview")
            report.append(f"- **Critical:** {attack_surface.get('critical_findings', 0)}")
            report.append(f"- **High:** {attack_surface.get('high_findings', 0)}")
            report.append(f"- **Medium:** {attack_surface.get('medium_findings', 0)}")
            report.append(f"- **Low:** {attack_surface.get('low_findings', 0)}")
            
            logging_gaps = detection.get("logging_gaps", [])
            if logging_gaps:
                report.append("\n### Identified Logging Gaps")
                for gap in logging_gaps:
                    report.append(f"- {gap}")
                    
            d3fend = detection.get("d3fend_mappings", [])
            if d3fend:
                report.append("\n### Recommended MITRE D3FEND Countermeasures")
                for d in d3fend:
                    report.append(f"- {d}")

        report.append("\n## Attack Module Execution")
        for idx, mod in enumerate(sim.module_results, 1):
            report.append(f"\n### {idx}. Module: `{mod.module}`")
            report.append(f"**Status:** {mod.status.upper()}")
            if mod.error:
                report.append(f"**Error:** {mod.error}")
                
            if not mod.findings:
                report.append("*No findings reported.*")
            else:
                report.append("#### Findings:")
                for f_idx, f in enumerate(mod.findings, 1):
                    report.append(f"\n**{idx}.{f_idx} {f.title}**")
                    report.append(f"- **Severity:** {f.severity.upper()}")
                    report.append(f"- **MITRE ID:** {f.mitre_id}")
                    report.append(f"- **Description:** {f.description}")
                    report.append(f"- **Remediation:** {f.remediation}")
                    report.append(f"\n**Payload / Evidence:**")
                    report.append(f"```text\n{f.evidence}\n```")

        sigma_rules = validation.get("sigma_rules", []) if validation else []
        if sigma_rules:
            report.append("\n## Payload-Specific Sigma Rules")
            report.append("The following Sigma rules have been dynamically generated based on the specific payloads utilized during this simulation. Deploy these rules to your SIEM to ensure detection of similar attacks.")
            
            for rule_wrapper in sigma_rules:
                if rule_wrapper.get("status") == "success":
                    mitre = rule_wrapper.get("mitre_id", "Unknown")
                    report.append(f"\n### Detection Rule for {mitre}")
                    report.append(f"```yaml\n{rule_wrapper.get('sigma_rule')}\n```")

        report.append("\n---\n*Report generated by SecureForge BAS Engine.*")
        return "\n".join(report)
