apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bas-engine-hpa
  namespace: secureforge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bas-engine
  minReplicas: 1
  maxReplicas: 5 # Scales up to 5 pods during heavy simulation loads
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70